<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "GALAXY",
    "slogan": "KEVA.APP",
    "description": "",
    "footer": "Load 60,000 Blocks (100 Days) <a href=https:\/\/github.com\/kevacoin-project\/keva_wallet\/releases target=_blank><font color=#28f428>Get Kevacoin wallet to view all and reply.<\/font><\/a>",
    "itemsPerPage": 6,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Asia\/Shanghai",
    "theme": "alternative",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "",
    "emailFrom": "no-reply@galaxyos.io",
    "orderBy": "date",
    "currentBuild": 20200320,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]"
}